// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMHcTeKklJlogoWScxQ6tyDVAg2OwSiZc',
    appId: '1:407358749235:web:7c63766486d1edfcb7c146',
    messagingSenderId: '407358749235',
    projectId: 'project-hermes-d667b',
    authDomain: 'project-hermes-d667b.firebaseapp.com',
    storageBucket: 'project-hermes-d667b.firebasestorage.app',
    measurementId: 'G-ZYX8PGJXFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqAP5Bc43P6KPpzLwcKtmwe0j9_y58PSE',
    appId: '1:407358749235:android:65688044175421cfb7c146',
    messagingSenderId: '407358749235',
    projectId: 'project-hermes-d667b',
    storageBucket: 'project-hermes-d667b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9V90Sbv1xnH0Hj6ut4GXOjM7di-Ms1C4',
    appId: '1:407358749235:ios:ccac3071c76f8d24b7c146',
    messagingSenderId: '407358749235',
    projectId: 'project-hermes-d667b',
    storageBucket: 'project-hermes-d667b.firebasestorage.app',
    iosBundleId: 'com.example.projectHermesFrontEnd',
  );
}
